//! GENERATED BY `unrdf sync`.
//!
//! This module is manufactured from admitted graph law.
//! Source: 
//!
//! # Access Admission Field
//!
//! Identifer: FIELD-ACCESS-BADGE

#![allow(dead_code)]

/// Presence of a named position in a field.
#[repr(u8)]
#[derive(Clone, Copy, Eq, PartialEq, Debug)]
pub enum Presence {
    Absent = 0,
    Present = 1,
}

#[repr(transparent)]
#[derive(Clone, Copy, Eq, PartialEq, Debug)]
pub struct BADGEPRESENTField(u8);

impl BADGEPRESENTField {
    /// Position 0: A badge was presented to the reader.
    pub const BADGE_PRESENT: u8 = 0b00000001;
    /// Position 1: The presented badge was recognized.
    pub const BADGE_RECOGNIZED: u8 = 0b00000010;
    /// Position 2: The badge holder is active.
    pub const HOLDER_ACTIVE: u8 = 0b00000100;
    /// Position 3: The door is allowed for this holder.
    pub const DOOR_ALLOWED: u8 = 0b00001000;
    /// Position 4: The time is allowed for this access attempt.
    pub const TIME_ALLOWED: u8 = 0b00010000;
    /// Position 5: The access attempt has been granted by rule.
    pub const GRANTED: u8 = 0b00100000;
    /// Position 6: The access attempt has been recorded.
    pub const RECORDED: u8 = 0b01000000;
    /// Position 7: The access attempt requires review.
    pub const REVIEW_REQUIRED: u8 = 0b10000000;

    pub const fn empty() -> Self {
        Self(0)
    }

    pub const fn raw(self) -> u8 {
        self.0
    }

    pub const fn with(mut self, position: u8) -> Self {
        self.0 |= position;
        self
    }

    pub const fn carries(self, position: u8) -> Presence {
        if self.0 & position != 0 {
            Presence::Present
        } else {
            Presence::Absent
        }
    }
}
