//! GENERATED BY `unrdf sync`.
//!
//! This module is manufactured from admitted graph law.
//! Source: 
//!
//! # Access Admission Field
//!
//! Identifer: FIELD-ACCESS-BADGE

#![allow(dead_code)]

/// Presence of a named position in a field.
#[repr(u8)]
#[derive(Clone, Copy, Eq, PartialEq, Debug)]
pub enum Presence {
    Absent = 0,
    Present = 1,
}

/// Selected continuation condition for an access attempt.
#[repr(u8)]
#[derive(Clone, Copy, Eq, PartialEq, Debug)]
pub enum AccessCondition {
    Grant = 0,
    Deny = 1,
    Review = 2,
}

#[repr(transparent)]
#[derive(Clone, Copy, Eq, PartialEq, Debug)]
pub struct AccessField(u8);

impl AccessField {
    /// Position 0: A badge was presented to the reader.
    pub const BADGE_PRESENT: u8 = 0x01;
    /// Position 1: The presented badge was recognized.
    pub const BADGE_RECOGNIZED: u8 = 0x02;
    /// Position 2: The badge holder is active.
    pub const HOLDER_ACTIVE: u8 = 0x04;
    /// Position 3: The door is allowed for this holder.
    pub const DOOR_ALLOWED: u8 = 0x08;
    /// Position 4: The time is allowed for this access attempt.
    pub const TIME_ALLOWED: u8 = 0x10;
    /// Position 5: The access attempt has been granted by rule.
    pub const GRANTED: u8 = 0x20;
    /// Position 6: The access attempt has been recorded.
    pub const RECORDED: u8 = 0x40;
    /// Position 7: The access attempt requires review.
    pub const REVIEW_REQUIRED: u8 = 0x80;

    pub const fn empty() -> Self {
        Self(0)
    }

    pub const fn raw(self) -> u8 {
        self.0
    }

    pub const fn with(mut self, position: u8) -> Self {
        self.0 |= position;
        self
    }

    pub const fn carries(self, position: u8) -> Presence {
        if self.0 & position != 0 {
            Presence::Present
        } else {
            Presence::Absent
        }
    }

    pub const fn select(self) -> AccessCondition {
        // Selection rule generated from ontology
        if self.0 & 0x1F == 0x1F {
            AccessCondition::Grant
        } else {
            AccessCondition::Deny
        }
    }
}

#[repr(C)]
#[derive(Clone, Copy, Eq, PartialEq, Debug)]
pub struct AccessAttempt {
    pub badge_id: u64,
    pub door_id: u32,
    pub epoch: u64,
    pub field: AccessField,
}

impl AccessAttempt {
    pub const fn new(badge_id: u64, door_id: u32, epoch: u64, field: AccessField) -> Self {
        Self { badge_id, door_id, epoch, field }
    }

    pub const fn select(self) -> AccessCondition {
        self.field.select()
    }

    pub const fn receipt(self, sequence: u64) -> AccessReceipt {
        AccessReceipt {
            badge_id: self.badge_id,
            door_id: self.door_id,
            epoch: self.epoch,
            sequence,
            access_raw: self.field.raw(),
            selected_condition: self.select() as u8,
        }
    }
}

#[repr(C)]
#[derive(Clone, Copy, Eq, PartialEq, Debug)]
pub struct AccessReceipt {
    pub badge_id: u64,
    pub door_id: u32,
    pub epoch: u64,
    pub sequence: u64,
    pub access_raw: u8,
    pub selected_condition: u8,
}
