//! GENERATED BY `unrdf sync`.
//!
//! This module is manufactured from admitted graph law.
//! Source: 
//!
//! # ConditionCode8 Field
//!
//! Identifer: FIELD-CONDITION8

#![allow(dead_code)]

/// Presence of a named position in a field.
#[repr(u8)]
#[derive(Clone, Copy, Eq, PartialEq, Debug)]
pub enum Presence {
    Absent = 0,
    Present = 1,
}

/// Selected continuation condition for an condition8 attempt.
#[repr(u8)]
#[derive(Clone, Copy, Eq, PartialEq, Debug)]
pub enum Condition8Condition {
    Grant = 0,
    Deny = 1,
    Review = 2,
}

#[repr(transparent)]
#[derive(Clone, Copy, Eq, PartialEq, Debug)]
pub struct Condition8Field(u8);

impl Condition8Field {
    /// Position 0: Outcome: Permitted.
    pub const OK: u8 = 0x01;
    /// Position 1: Outcome: Permitted with audit flag.
    pub const WARN: u8 = 0x02;
    /// Position 2: Outcome: Terminated by safety gate.
    pub const BLOCKED: u8 = 0x04;
    /// Position 3: Outcome: Transient failure, re-attempt allowed.
    pub const RETRY: u8 = 0x08;
    /// Position 4: Outcome: Human-in-the-loop required.
    pub const ESCALATE: u8 = 0x10;
    /// Position 5: Outcome: Policy violation, motion denied.
    pub const REFUSE: u8 = 0x20;
    /// Position 6: Outcome: Abnormal end, system panic.
    pub const ABEND: u8 = 0xAB;
    /// Position 7: Outcome: Undefined behavior.
    pub const UNKNOWN: u8 = 0xFF;

    pub const fn empty() -> Self {
        Self(0)
    }

    pub const fn raw(self) -> u8 {
        self.0
    }

    pub const fn with(mut self, position: u8) -> Self {
        self.0 |= position;
        self
    }

    pub const fn carries(self, position: u8) -> Presence {
        if self.0 & position != 0 {
            Presence::Present
        } else {
            Presence::Absent
        }
    }

    pub const fn select(self) -> Condition8Condition {
        // Selection rule generated from ontology
        if self.0 & 0x1F == 0x1F {
            Condition8Condition::Grant
        } else {
            Condition8Condition::Deny
        }
    }
}

#[repr(C)]
#[derive(Clone, Copy, Eq, PartialEq, Debug)]
pub struct Condition8Attempt {
    pub badge_id: u64,
    pub door_id: u32,
    pub epoch: u64,
    pub field: Condition8Field,
}

impl Condition8Attempt {
    pub const fn new(badge_id: u64, door_id: u32, epoch: u64, field: Condition8Field) -> Self {
        Self { badge_id, door_id, epoch, field }
    }

    pub const fn select(self) -> Condition8Condition {
        self.field.select()
    }

    pub const fn receipt(self, sequence: u64) -> Condition8Receipt {
        Condition8Receipt {
            badge_id: self.badge_id,
            door_id: self.door_id,
            epoch: self.epoch,
            sequence,
            access_raw: self.field.raw(),
            selected_condition: self.select() as u8,
        }
    }
}

#[repr(C)]
#[derive(Clone, Copy, Eq, PartialEq, Debug)]
pub struct Condition8Receipt {
    pub badge_id: u64,
    pub door_id: u32,
    pub epoch: u64,
    pub sequence: u64,
    pub access_raw: u8,
    pub selected_condition: u8,
}
