//! GENERATED BY `unrdf sync`.
//!
//! This module is manufactured from admitted graph law.
//! Source: 
//!
//! # Status8 Field
//!
//! Identifer: FIELD-STATUS8

#![allow(dead_code)]

/// Presence of a named position in a field.
#[repr(u8)]
#[derive(Clone, Copy, Eq, PartialEq, Debug)]
pub enum Presence {
    Absent = 0,
    Present = 1,
}

/// Selected continuation condition for an status8 attempt.
#[repr(u8)]
#[derive(Clone, Copy, Eq, PartialEq, Debug)]
pub enum Status8Condition {
    Grant = 0,
    Deny = 1,
    Review = 2,
}

#[repr(transparent)]
#[derive(Clone, Copy, Eq, PartialEq, Debug)]
pub struct Status8Field(u8);

impl Status8Field {
    /// Position 0: The system is in a normal operational state.
    pub const OK: u8 = 0x01;
    /// Position 1: The system has detected a non-blocking anomaly.
    pub const WARN: u8 = 0x02;
    /// Position 2: The system is prevented from moving forward.
    pub const BLOCKED: u8 = 0x04;
    /// Position 3: The state cannot be determined.
    pub const UNKNOWN: u8 = 0x08;
    /// Position 4: The operation was intentionally bypassed.
    pub const SKIPPED: u8 = 0x10;
    /// Position 5: The evidence supporting the status is out of date.
    pub const STALE: u8 = 0x20;
    /// Position 6: The status has been immutably recorded.
    pub const RECEIPTED: u8 = 0x40;
    /// Position 7: The status transition can be deterministically replayed.
    pub const REPLAYABLE: u8 = 0x80;

    pub const fn empty() -> Self {
        Self(0)
    }

    pub const fn raw(self) -> u8 {
        self.0
    }

    pub const fn with(mut self, position: u8) -> Self {
        self.0 |= position;
        self
    }

    pub const fn carries(self, position: u8) -> Presence {
        if self.0 & position != 0 {
            Presence::Present
        } else {
            Presence::Absent
        }
    }

    pub const fn select(self) -> Status8Condition {
        // Selection rule generated from ontology
        if self.0 & 0x1F == 0x1F {
            Status8Condition::Grant
        } else {
            Status8Condition::Deny
        }
    }
}

#[repr(C)]
#[derive(Clone, Copy, Eq, PartialEq, Debug)]
pub struct Status8Attempt {
    pub badge_id: u64,
    pub door_id: u32,
    pub epoch: u64,
    pub field: Status8Field,
}

impl Status8Attempt {
    pub const fn new(badge_id: u64, door_id: u32, epoch: u64, field: Status8Field) -> Self {
        Self { badge_id, door_id, epoch, field }
    }

    pub const fn select(self) -> Status8Condition {
        self.field.select()
    }

    pub const fn receipt(self, sequence: u64) -> Status8Receipt {
        Status8Receipt {
            badge_id: self.badge_id,
            door_id: self.door_id,
            epoch: self.epoch,
            sequence,
            access_raw: self.field.raw(),
            selected_condition: self.select() as u8,
        }
    }
}

#[repr(C)]
#[derive(Clone, Copy, Eq, PartialEq, Debug)]
pub struct Status8Receipt {
    pub badge_id: u64,
    pub door_id: u32,
    pub epoch: u64,
    pub sequence: u64,
    pub access_raw: u8,
    pub selected_condition: u8,
}
